---
- name: Install Fail2Ban
  apt:
    name=fail2ban
    update_cache=yes

- name: Configure Fail2Ban main configuration for Ubuntu 14.04 LTS
  template:
    src=jail.conf.1404
    dest=/etc/fail2ban/jail.conf
    owner=root
    group=root
    mode=0640
    force=yes
  notify: reload fail2ban
  when: 
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version == "14.04"

- name: Configure Fail2Ban main configuration for Ubuntu 16.04 LTS
  template:
    src=jail.j2
    dest=/etc/fail2ban/jail.d/jail.local
    owner=root
    group=root
    mode=0640
    force=yes
  notify: reload fail2ban
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version == "16.04"
